- name: Setup Redis and Frontend Servers
  hosts:
    - server_role_redis_server
    - server_role_frontend_server
      #these are specifying the host we using
  become: true
  gather_facts: yes # Collect facts only once for the entire play


  roles:
    - redis
    - frontend
